# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/kernel/motorola/sm7325/techpack/audio/include
EXTRA_CFLAGS += -I$(TOP)/kernel/motorola/sm7325/techpack/audio/include/uapi/

EXTRA_CFLAGS += -DCONFIG_AW882XX_CODEC -DCONFIG_AW882XX_DSP

CONFIG_AW882XX_K504 ?= y

aw882xx_k504-objs = aw882xx.o
obj-$(CONFIG_AW882XX_K504) += aw882xx_k504.o
