# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include

CONFIG_MMI_RELAY ?= y
obj-$(CONFIG_MMI_RELAY) += mmi_relay.o
